// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvOLjMUHlsU4PqNquVbIkvEMWkmFkLugA',
    appId: '1:942271874830:web:c4faf25a100a154f17795f',
    messagingSenderId: '942271874830',
    projectId: 'paola-app-firebase-f89f7',
    authDomain: 'paola-app-firebase-f89f7.firebaseapp.com',
    storageBucket: 'paola-app-firebase-f89f7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkLFW-CYvZANPsMTe47BqqaMkfxQMizFE',
    appId: '1:942271874830:android:7e3a6dadeeb1bf8a17795f',
    messagingSenderId: '942271874830',
    projectId: 'paola-app-firebase-f89f7',
    storageBucket: 'paola-app-firebase-f89f7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDktzgZjWtmbxcRN7DDo5OpzNGyf447-r0',
    appId: '1:942271874830:ios:79dd29556b8ce03817795f',
    messagingSenderId: '942271874830',
    projectId: 'paola-app-firebase-f89f7',
    storageBucket: 'paola-app-firebase-f89f7.firebasestorage.app',
    iosBundleId: 'com.example.miAppFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDktzgZjWtmbxcRN7DDo5OpzNGyf447-r0',
    appId: '1:942271874830:ios:79dd29556b8ce03817795f',
    messagingSenderId: '942271874830',
    projectId: 'paola-app-firebase-f89f7',
    storageBucket: 'paola-app-firebase-f89f7.firebasestorage.app',
    iosBundleId: 'com.example.miAppFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvOLjMUHlsU4PqNquVbIkvEMWkmFkLugA',
    appId: '1:942271874830:web:ad4d06dc4a874daa17795f',
    messagingSenderId: '942271874830',
    projectId: 'paola-app-firebase-f89f7',
    authDomain: 'paola-app-firebase-f89f7.firebaseapp.com',
    storageBucket: 'paola-app-firebase-f89f7.firebasestorage.app',
  );
}
